name: BDD

on:
  push:
    branches:
      - main
    paths:
      - 'new'
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Printing Hello World
        run: echo "Hello world"
