# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: main
    paths:
      - views/form.html

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 15

      - name: Install dependencies
        run: npm install
        
      - name: jsDom for Tests 
        run: npm install jsdom --save-dev

      - name: Run tests
        run: npx jest
